### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by zyyv** [developer-plus/developer-plus#22]
- 使用`rem` 替换 `px`单位
- 可以讨论出一套团队使用的`theme color`
- 多用`vueuse hook` 优化代码
- 多用`unocss`，减少css的书写
- 少用第三方依赖库，能手写的尽量手写
- 如果可以，建议朴素风格，减少花里胡哨
- etc.

**Comment by alexzhang1030** [comment]
感谢您的建议，我们会认真考虑

**Comment by RainyNight9** [comment]
第三个的理解，我认为就是可以从源码中拷贝出来对应的 hook ，直接在项目中使用，这样还有助于学习源码，学习其编成思想... 是这么意思吧？

**Comment by LoTwT** [comment]
个人认为第三条和第五条表面上存在一定程度的冲突，请问大佬可以举一些更具体的例子，演示一下具体场景吗？

**Comment by Hongbusi** [comment]
目前的计划是，准备快速完成第一个版本的官网。周刊、todolist、书签都需要官网作为入口，用来减短用户的参与链路。所以优化主要放在后续的迭代中。

响应式、主题色、减少第三方依赖...后续都要去做，不过现在还不是时候。

另外，zx 太客气了，要知道现在我们是一个 team。
