### ISSUE TITLE
the tabs component style does not match the overall style and are a bit weird in dark mode.

### ISSUE THREAD

**Issue by yekezz** [developer-plus/developer-plus#31]
the tabs component style does not match the overall style and are a bit weird in dark mode.
![image](https://user-images.githubusercontent.com/41691876/169222976-055917f3-6dc7-45eb-aa42-1b2e6e8c2927.png)
![image](https://user-images.githubusercontent.com/41691876/169223032-a8f02e06-3ded-4251-a285-659d152b5866.png)

**Comment by Hongbusi** [comment]
（其实可以用中文交流的。）

这里目前还正在完善，不过还是要多谢你的贡献 ～🎉

**Comment by alexzhang1030** [comment]
这里会进行重构，请关注
