### ISSUE TITLE
官网打字机处可以选择一款不错的终端字体替换

### ISSUE THREAD

**Issue by luckept** [developer-plus/developer-plus#34]
字体颜色也可以考虑绿色哈哈
效果或许可参考下图
![image](https://user-images.githubusercontent.com/83466315/169302610-e0f2c4f4-54e4-419d-bd9f-d7028a970eeb.png)

**Comment by Hongbusi** [comment]
字体可以搞一下看看效果，官网颜色的话主要就是黑白灰，暂不考虑其他颜色。
