### ISSUE TITLE
关于【开发计划】模块优化的探讨

### ISSUE THREAD

**Issue by luckept** [developer-plus/developer-plus#48]
# 描述问题

目前官网【开发计划】模块处如果频繁点击 Tab 会导致频繁向 GitHub API 发送请求，同时页面的快速切换也会让用户观感不佳

# 优化方向

考虑到【开发计划】模块处的数据通常不会频繁更新，或许只在进入模块的时候一次性获取到所有的数据即可

# 面临的问题

接口返回的数据数量存在上限，分页功能的设计和实现仍需讨论

**Comment by luckept** [comment]
# 或许需要先探讨

请求是在加载下一页的时候做，还是一开始就设法拿到所有的数据，分页仅仅是优化展示效果

**Comment by Hongbusi** [comment]
一次性拿所有的数据，看起是没必要的。

如果把三个分类的数据分开保存，首次切换 tab 加载每个分类的前 30 条，后面只有点击加载更多才会继续发请求。

这样看起来也比较合理。

**Comment by luckept** [comment]
> 一次性拿所有的数据，看起是没必要的。
> 
> 如果把三个分类的数据分开保存，首次切换 tab 加载每个分类的前 30 条，后面只有点击加载更多才会继续发请求。
> 
> 这样看起来也比较合理。

我看了看接口返回值，好像没有看到总数，如何知道是否是最后一页呢，还是说不做处理，在没有更多数据的时候点击加载更多还是走默认流程。
或者根据拿到的数组长度做判断，看它是否有新数据。
