### ISSUE TITLE
开发计划页，数据较多时，右侧出现原生滚动条

### ISSUE THREAD

**Issue by LoTwT** [developer-plus/developer-plus#51]
目前仅在 Tab 为 Done 时出现，可以考虑美化滚动条，或其他交互方式。

**Comment by luckept** [comment]
我刚通过 #52 提交了一个对该问题的初步优化方案，利用 css 的 overflow-y: overlay 来消除滚动条出现后对界面的挤压，至于样式优化，可能还需要等大家共同讨论后决定
