### ISSUE TITLE
是否考虑在首页使用骨架屏或者让第二次数据走缓存来提升加载首页的速度

### ISSUE THREAD

**Issue by luckept** [developer-plus/developer-plus#55]
目前导航栏切回首页时由于先请求了数据所以页面会隔一会儿才出现，体验上不如先进入页面后再请求数据，而原本空间的占位或许也可通过骨架屏优化

**Comment by luckept** [comment]
或者如果首页数据变动不大的话也可以考虑第二次进入该页面时数据走缓存，类似 vuex，仅仅当用户刷新页面时才重新请求，这样可以避免维护骨架屏的负担

**Comment by Hongbusi** [comment]
想法很赞。

除了通过 github 的接口获取的数据，其他都可以说是静态数据（通过 nuxt3 的 server/api 实现）。

**Comment by luckept** [comment]
可是通过 nuxt3 的 server/api 实现静态数据的话，仍然需要使用 $fetch 获取数据，我尝试了一下，这个过程仍然是有延迟的，或者是我理解错啦哈哈，可能没太理解这里说的（通过 nuxt3 的 server/api 实现）
